/**
 * Assembles scripts/i18n-data/student-health-translations.mjs from per-locale JSON.
 * Run: node scripts/i18n-data/student-health/assemble.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "../../..");
const OUT = join(HERE, "../student-health-translations.mjs");
const EN = JSON.parse(readFileSync(join(ROOT, "messages/en.json"), "utf8")).studentHealth;

const LOCALES = ["it", "sq", "rom", "ro", "hu", "sk", "cs", "bg", "sr", "hr", "bs", "mk", "sl", "el", "tr"];
const translations = { en: EN };

for (const locale of LOCALES) {
  const path = join(HERE, `${locale}.json`);
  translations[locale] = JSON.parse(readFileSync(path, "utf8"));
}

const body = `/**
 * Full studentHealth namespace translations for all supported locales.
 * Generated by scripts/i18n-data/student-health/assemble.mjs
 */
export const TRANSLATIONS = ${JSON.stringify(translations, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`Wrote ${OUT} (${LOCALES.length + 1} locales)`);
