import { readFileSync, writeFileSync } from "fs";

const ro = JSON.parse(readFileSync("./messages/ro.json", "utf8"));

function setNested(obj, path, val) {
  const parts = path.split(".");
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!cur[parts[i]]) cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  if (cur[parts[parts.length - 1]] === undefined) {
    cur[parts[parts.length - 1]] = val;
  }
}

const patch = {
  "chat.placeholder": "Întreabă-mă orice despre sănătate…",
  "chat.thinking": "Mă gândesc…",
  "chat.errorMessage": "Nu mă pot conecta. Verifică internetul și încearcă din nou.",
  "chat.errorRateLimit": "Trimiți mesaje prea repede. Așteaptă un moment și încearcă din nou.",
  "chat.errorServiceUnavailable": "Serviciul AI nu este disponibil acum. Încearcă din nou în un minut.",
  "chat.errorUpstream": "Serviciul AI a întâmpinat o eroare. Încearcă din nou.",
  "chat.disclaimer": "Sunt un consilier de sănătate, nu un medic. În urgențe, sună întotdeauna la 112.",
  "chat.emergencyCall": "Urgență? Sună",
  "chat.suggestedQuestions": "Oamenii întreabă des",
  "chat.q1": "Soacra mea spune că vaccinurile cauzează autism. Este adevărat?",
  "chat.q2": "Copilul meu are febră de 2 zile. Ce trebuie să fac?",
  "chat.q3": "Pe Facebook scrie că medicina pentru diabet este otravă și ar trebui să folosești plante",
  "chat.q4": "Sunt însărcinată și mi-e frică să merg la spital. Care sunt drepturile mele?",
  "chat.q5": "Mă simt tristă tot timpul și nu pot dormi. Este normal?",
  "chat.q6": "Cum mă înregistrez la un medic dacă nu am documente?",
  "chat.askMeAnything": "Întreabă-mă orice",
  "chat.heroArtAlt": "Ilustrație a unui companion de sănătate de încredere.",
  "chat.inputAria": "Scrie întrebarea ta de sănătate",
  "chat.sendAria": "Trimite mesaj",
  "chat.meta.title": "Sfaturi — Redi Health",
  "chat.meta.description": "Pune orice întrebare despre sănătate. Primești răspunsuri clare și de încredere.",

  "scan.title": "Verifică o afirmație despre sănătate",
  "scan.subtitle": "Lipește ceva ce ai văzut pe Facebook, TikTok sau WhatsApp. Îți spunem adevărul.",
  "scan.checkButton": "Verifică",
  "scan.checking": "Verificând…",
  "scan.shareButton": "Distribuie adevărul",
  "scan.recentChecks": "Verificări recente",
  "scan.orDescribe": "sau descrie ce ai auzit",
  "scan.verdictVerified": "Verificat",
  "scan.verdictMisleading": "Înșelător",
  "scan.verdictFalse": "Fals",
  "scan.verdictUnclear": "Neclar",
  "scan.inputAria": "Lipește afirmația de sănătate pentru verificare",
  "scan.sourceLabel": "Sursă",
  "scan.shareTagline": "Verificat de Redi Health Advisor",
  "scan.shareTitle": "Verificare de fapt sanitar",
  "scan.errors.analyze": "Nu s-a putut analiza afirmația",
  "scan.errors.network": "Eroare de rețea. Verificați conexiunea.",
  "scan.meta.title": "Verificare de fapte — Redi Health",
  "scan.eyebrow": "Verificare de fapte",
  "scan.heroArtAlt": "Ilustrație reprezentând demontarea miturilor și afirmațiile sanitare verificate.",

  "explain.heroTitle": "Înțelege prescripția ta",
  "explain.heroSubtitle": "Scrie diagnosticul sau numele medicamentului. Îl explicăm cu cuvinte simple.",
  "explain.heroArtAlt": "Ilustrație de sprijin în stil farmacist pentru decodificarea unei prescripții.",
  "explain.inputAria": "Introdu diagnosticul sau numele medicamentului",
  "explain.cta": "Explică",
  "explain.ctaAnalyzing": "Analizând…",
  "explain.examplesHeading": "Exemple comune",
  "explain.loading": "Citind prescripția ta…",
  "explain.sections.whatThisMeans": "Ce înseamnă",
  "explain.sections.whyItMatters": "De ce contează",
  "explain.sections.ifIgnored": "Dacă ignori",
  "explain.sections.medicationsTitle": "Medicamentele tale",
  "explain.sections.howToTake": "Cum să iei",
  "explain.sections.sideEffects": "Efecte secundare",
  "explain.sections.neverDo": "Nu face niciodată",
  "explain.sections.questionsTitle": "Întreabă medicul data viitoare",
  "explain.sections.tipsTitle": "Ce poți face astăzi",
  "explain.sections.emergencyTitle": "Mergi la spital dacă",
  "explain.anotherCta": "Explică altă prescripție",
  "explain.disclaimerBold": "Nu este sfat medical.",
  "explain.disclaimerBody": "Acest instrument explică termenii medicali cu cuvinte simple. Urmați întotdeauna instrucțiunile medicului.",
  "explain.meta.title": "Înțelege prescripția — Redi Health",
  "explain.meta.description": "Primești diagnosticul și medicamentele explicate cu cuvinte simple",
  "explain.takePhoto": "Fă o fotografie",
  "explain.uploadImage": "Încarcă imagine",
  "explain.placeholderWithImage": "(Opțional) Adaugă context suplimentar — vârsta, cum îl iei, ce te îngrijorează…",
  "explain.imagePreviewAlt": "Previzualizare fotografie prescripție",
  "explain.imageReady": "Fotografie gata",
  "explain.imageReadyBody": "Vom citi medicamentul, doza și instrucțiunile și vom explica totul cu cuvinte simple.",
  "explain.imageRemove": "Elimină fotografia",
  "explain.preparingImage": "Pregătind fotografia…",
  "explain.imageFailed": "Nu s-a putut citi fotografia. Încearcă alta.",

  "navigate.heroTitle": "Trebuie să văd un medic",
  "navigate.heroSubtitle": "Te vom ajuta să te pregătești — ce să aduci, ce să spui, drepturile tale.",
  "navigate.issuePrompt": "Care este problema?",
  "navigate.issues.fever": "Febră / Infecție",
  "navigate.issues.pain": "Durere / Rănire",
  "navigate.issues.pregnancy": "Sarcină",
  "navigate.issues.chronic": "Afecțiune cronică",
  "navigate.issues.mental": "Sănătate mintală",
  "navigate.issues.skin": "Piele / Ochi / Urechi",
  "navigate.issues.child": "Copil bolnav",
  "navigate.issues.other": "Altceva",
  "navigate.tellMore": "Spune-ne mai mult",
  "navigate.detailPlaceholder": "Descrie ce se întâmplă… De cât timp? Cât de grav?",
  "navigate.detailAria": "Descrie problema ta de sănătate",
  "navigate.insuranceTitle": "Ai asigurare de sănătate?",
  "navigate.insuranceSubtitle": "Asta ne ajută să îți spunem ce să aduci",
  "navigate.insuranceYes": "Da, am card de sănătate (CNAS)",
  "navigate.insuranceNo": "Nu, nu am asigurare",
  "navigate.insuranceUnknown": "Nu sunt sigur",
  "navigate.countryTitle": "În ce țară ești?",
  "navigate.generating": "Pregătind fișa ta de vizită…",
  "navigate.generateCard": "Generează fișa de vizită medicală",
  "navigate.startOver": "Începe din nou",
  "navigate.showDoctor": "Arată asta medicului",
  "navigate.generatedBy": "Generat de Redi Health Advisor",
  "navigate.whatToBring": "Ce să aduci",
  "navigate.askYourDoctor": "Întreabă medicul",
  "navigate.patientRights": "Drepturile tale ca pacient",
  "navigate.findHospital": "Găsește îngrijire în apropiere",
  "navigate.mapHint": "Deschide harta cu indicații",
  "navigate.meta.title": "Navigator medical — Redi Health",
  "navigate.meta.description": "Pregătește-te pentru vizita medicală — fișă de vizită, ce să aduci, drepturile tale.",

  "about.brand": "Redi Health",
  "about.tagline": "Alfabetizare în sănătate pentru comunități rurale și excluse",
  "about.version": "Versiunea 1.0.0",
  "about.missionBody": "Redi Health este un companion AI co-conceput cu mediatori de teren și clinicieni pentru cartierele pe care sistemele de sănătate oficiale le deservesc insuficient — de la municipii rurale la așezări informale — cu atenție profundă față de comunitățile rome.",
  "about.values.careLabel": "Construit cu grijă",
  "about.values.careDesc": "De mediatori sanitari",
  "about.values.languagesLabel": "16 limbi",
  "about.values.languagesDesc": "În toată Europa",
  "about.values.evidenceLabel": "Bazat pe dovezi",
  "about.values.evidenceDesc": "Ghiduri OMS",
  "about.values.communityLabel": "Comunitatea pe primul loc",
  "about.values.communityDesc": "Fără judecată",
  "about.privacyLink": "Politica de confidențialitate",
  "about.termsLink": "Termeni și condiții",
  "about.disclaimer": "Redi Health nu este un dispozitiv medical. Toate informațiile sunt doar în scop educațional. Consultați întotdeauna un profesionist calificat în domeniul sănătății pentru decizii medicale.",
  "about.meta.title": "Despre — Redi Health",
  "about.meta.description": "Despre platforma de alfabetizare Redi Health",

  "footer.tagline": "Alfabetizare multilingvă pentru comunitățile dezavantajate, rurale și rome din Europa.",
  "footer.product": "Produs",
  "footer.forStudents": "Pentru studenți",
  "footer.forCommunity": "Pentru comunitate",
  "footer.forMinisters": "Pentru parteneri",
  "footer.company": "Companie",
  "footer.methodology": "Metodologie",
  "footer.impact": "Impact",
  "footer.privacy": "Confidențialitate",
  "footer.contact": "Contact",
  "footer.rights": "© 2026 Redi Health. Toate drepturile rezervate.",
  "footer.builtWith": "Construit cu mediatori sanitari romi din 15 țări.",
  "footer.systemsOperational": "Toate sistemele operaționale",

  "providers.title": "Găsește îngrijire medicală",
  "providers.subtitle": "Caută servicii medicale în apropierea ta. Contactează furnizorii direct pentru a confirma disponibilitatea.",
  "providers.searchPlaceholder": "Caută după oraș sau numele clinicii…",
  "providers.allRegions": "Toate regiunile",
  "providers.verified": "Romă-prietenos verificat",
  "providers.freeClinic": "Servicii gratuite disponibile",
  "providers.interpreter": "Interpret Romani",
  "providers.getDirections": "Obține indicații",

  "more.metaTitle": "Toate funcționalitățile",
  "more.metaDescription": "Fiecare instrument Redi Health într-un singur loc",
  "more.title": "Toate funcționalitățile",
  "more.sections.tools": "Instrumente de sănătate",
  "more.sections.learn": "Învață și crește",
  "more.sections.professional": "Profesional",
  "more.sections.account": "Cont",
  "more.items.scanLabel": "Scanner dezinformare",
  "more.items.scanDesc": "Verifică afirmații despre sănătate",
  "more.items.symptomsLabel": "Verificare simptome",
  "more.items.symptomsDesc": "Atinge unde doare",
  "more.items.consultLabel": "Consultație de sănătate",
  "more.items.consultDesc": "Consultație ghidată de AI",
  "more.items.vaccinesLabel": "Ghid de vaccinuri",
  "more.items.vaccinesDesc": "Fiecare vaccin explicat",
  "more.items.navigateLabel": "Navigator medical",
  "more.items.navigateDesc": "Găsește un medic, cunoaște-ți drepturile",
  "more.items.topicsLabel": "Subiecte de sănătate",
  "more.items.topicsDesc": "Șase zone de sănătate cu lecții",
  "more.items.studentsLabel": "Academia de sănătate pentru studenți",
  "more.items.studentsDesc": "Prim ajutor, BTS, vaccinuri — învățare progresivă",
  "more.items.quizLabel": "Quiz de sănătate",
  "more.items.quizDesc": "Testează-ți cunoștințele",
  "more.items.glossaryLabel": "Glosar medical",
  "more.items.glossaryDesc": "Termeni medicali explicați simplu",
  "more.items.rightsLabel": "Cunoaște-ți drepturile",
  "more.items.rightsDesc": "Drepturile pacientului și ajutor juridic",
  "more.items.storiesLabel": "Povești din comunitate",
  "more.items.storiesDesc": "Experiențe reale din comunitățile rome",
  "more.items.regionsLabel": "Comunități rome",
  "more.items.regionsDesc": "Informații de sănătate pe țară",
  "more.items.mediatorLabel": "Dashboard mediator",
  "more.items.mediatorDesc": "Instrumente pentru mediatori sanitari",
  "more.items.profileLabel": "Profil",
  "more.items.profileDesc": "Limbă, progres, date",
  "more.items.aboutLabel": "Despre Redi Health",
  "more.items.aboutDesc": "Versiune, confidențialitate, contact",

  "privacy.title": "Politica de confidențialitate",
  "privacy.subtitle": "Ce colectăm, de ce și cum îl poți controla.",
  "privacy.lastUpdated": "Ultima actualizare: {date}",
  "privacy.actionsTitle": "Drepturile tale privind datele",
  "privacy.actionsSubtitle": "Exportă sau șterge toate datele tale.",
  "privacy.exportLabel": "Exportă datele mele",
  "privacy.exportHint": "Descarcă toate datele de pe server într-un fișier JSON.",
  "privacy.deleteLabel": "Șterge contul meu",
  "privacy.deleteHint": "Elimină permanent toate datele tale de pe server.",
  "privacy.deleteConfirmTitle": "Ești sigur?",
  "privacy.deleteConfirmBody": "Aceasta elimină câmpurile tale de identificare acum. Contul nu poate fi recuperat. Ștergerea definitivă se finalizează în 30 de zile.",
  "privacy.deleteConfirmCta": "Da, șterge contul meu",
  "privacy.deleteCancel": "Anulează",
  "privacy.authRequired": "Exportul de pe server necesită un cont. Datele locale pot fi descărcate folosind butonul de mai sus.",
  "privacy.unavailable": "Serviciu indisponibil. Încearcă mai târziu.",
  "privacy.successDeleted": "Datele tale au fost eliminate. La revedere.",
  "privacy.disclaimer": "Redi Health nu este un dispozitiv medical și nu oferă sfaturi medicale. Tot conținutul generat de AI este doar în scop educațional.",
  "privacy.sections.collect.title": "Ce colectăm",
  "privacy.sections.collect.body": "Cont, preferințe, progresul lecțiilor, check-in-urile de dispoziție și apă pe care le înregistrezi, și înregistrări de audit. Nu colectăm prompturi AI brute sau note de teren — acestea rămân pe dispozitivul tău.",
  "privacy.sections.use.title": "Cum îl utilizăm",
  "privacy.sections.use.body": "Personalizăm academia, prevenim abuzurile și îmbunătățim conținutul. Nu vindem niciodată datele tale. Utilizăm analize anonime când sunt activate și respectăm Do-Not-Track.",
  "privacy.sections.storage.title": "Unde locuiesc",
  "privacy.sections.storage.body": "Contul și progresul tău sunt stocate în Supabase Postgres din regiunea UE. Notele de teren, seriile și XP-ul sunt locale pe dispozitiv.",
  "privacy.sections.processors.title": "Procesatori terți",
  "privacy.sections.processors.body": "OpenAI (AI), Supabase (bază de date), Sentry (erori), Langfuse (trasabilitate AI), PostHog (analize anonime), Resend (email), Upstash (limitare rată).",
  "privacy.sections.rights.title": "Drepturile tale",
  "privacy.sections.rights.body": "Sub GDPR: acces, rectificare, ștergere, portabilitate, restricție, obiecție. Utilizează butonul de mai sus sau contactează dpo@redi.healthcare.",
  "privacy.sections.transfers.title": "Transferuri internaționale",
  "privacy.sections.transfers.body": "Procesatorii care operează în afara UE funcționează sub clauze contractuale standard. Preferăm găzduirea în regiunea UE.",
  "privacy.sections.deletion.title": "Ștergere și retenție",
  "privacy.sections.deletion.body": "Ștergerea soft la cerere; ștergerea definitivă în 30 de zile. Jurnalele de sănătate păstrate 5 ani sau până la ștergere. Jurnalele de audit păstrate 1 an.",
  "privacy.sections.contact.title": "Contact",
  "privacy.sections.contact.body": "Responsabil cu protecția datelor: dpo@redi.healthcare. SLA de 30 de zile pentru cererile persoanelor vizate.",
  "privacy.metaTitle": "Confidențialitate — Redi Health",
  "privacy.metaDescription": "Politica de confidențialitate Redi Health",
};

for (const [key, val] of Object.entries(patch)) {
  setNested(ro, key, val);
}

writeFileSync("./messages/ro.json", JSON.stringify(ro, null, 2) + "\n");
console.log("Updated ro.json with", Object.keys(patch).length, "Romanian translations");
